### ISSUE TITLE
why this is empty

### ISSUE THREAD

**Issue by xingzhefeng** [xmindltd/xmind-sdk-java#2]
your are gantt  has lot of bugs .we want to help Resolved .!
Come on! I love this project!

**Comment by nielinjie** [comment]
empty still.

**Comment by seveniruby** [comment]
+1

**Comment by vittee** [comment]
+1

**Comment by zhuxiangzx** [comment]
+1

**Comment by oychao** [comment]
+1

**Comment by frankshaka** [comment]
This repository is deprecated. Please refer to [this wiki](https://github.com/xmindltd/xmind/wiki/UsingXmindAPI) for how to manipulate with XMind files using Java and the [source of "org.xmind.core" bundle](https://github.com/xmindltd/xmind/tree/master/bundles/org.xmind.core).
