### ISSUE TITLE
快开发啊

### ISSUE THREAD

**Issue by runlittlesun** [xmindltd/xmind-sdk-java#3]
怎么是空的？等着用呢。 快开发啊

**Comment by frankshaka** [comment]
This repository is deprecated. Please refer to [this wiki](https://github.com/xmindltd/xmind/wiki/UsingXmindAPI) for how to manipulate with XMind files using Java and the [source of "org.xmind.core" bundle](https://github.com/xmindltd/xmind/tree/master/bundles/org.xmind.core).
